# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 585)
        MainWindow.setStyleSheet("")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stacked_widget = QtWidgets.QStackedWidget(self.central_widget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setStyleSheet("")
        self.welcome_page.setObjectName("welcome_page")
        self.gridLayout = QtWidgets.QGridLayout(self.welcome_page)
        self.gridLayout.setObjectName("gridLayout")
        self.welcome_page_label = QtWidgets.QLabel(self.welcome_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_page_label.sizePolicy().hasHeightForWidth())
        self.welcome_page_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Wide Latin")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.welcome_page_label.setFont(font)
        self.welcome_page_label.setStyleSheet("color: #0077b6;")
        self.welcome_page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_page_label.setWordWrap(False)
        self.welcome_page_label.setObjectName("welcome_page_label")
        self.gridLayout.addWidget(self.welcome_page_label, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.welcome_page_data_mode_button = QtWidgets.QPushButton(self.welcome_page)
        self.welcome_page_data_mode_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(15)
        self.welcome_page_data_mode_button.setFont(font)
        self.welcome_page_data_mode_button.setStyleSheet("QPushButton  {\n"
"color: #fff;\n"
"background-color: #0077b6;\n"
"border-radius: 10px;\n"
"border: 1px solid #74D0E7;\n"
"}\n"
"\n"
"QPushButton :hover{\n"
"background-color: #74D0E7;\n"
"}")
        self.welcome_page_data_mode_button.setObjectName("welcome_page_data_mode_button")
        self.horizontalLayout.addWidget(self.welcome_page_data_mode_button)
        self.welcome_page_cv_mode_button = QtWidgets.QPushButton(self.welcome_page)
        self.welcome_page_cv_mode_button.setEnabled(False)
        self.welcome_page_cv_mode_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(15)
        self.welcome_page_cv_mode_button.setFont(font)
        self.welcome_page_cv_mode_button.setStyleSheet("")
        self.welcome_page_cv_mode_button.setCheckable(False)
        self.welcome_page_cv_mode_button.setObjectName("welcome_page_cv_mode_button")
        self.horizontalLayout.addWidget(self.welcome_page_cv_mode_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.stacked_widget.addWidget(self.welcome_page)
        self.data_mode_page = QtWidgets.QWidget()
        self.data_mode_page.setObjectName("data_mode_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.data_mode_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.data_mode_page_file_button = QtWidgets.QPushButton(self.data_mode_page)
        self.data_mode_page_file_button.setObjectName("data_mode_page_file_button")
        self.horizontalLayout_2.addWidget(self.data_mode_page_file_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 1, 1, 1)
        self.stacked_widget.addWidget(self.data_mode_page)
        self.cv_mode_page = QtWidgets.QWidget()
        self.cv_mode_page.setObjectName("cv_mode_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cv_mode_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.cv_mode_page)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stacked_widget.addWidget(self.cv_mode_page)
        self.verticalLayout.addWidget(self.stacked_widget)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataManagerApp"))
        self.welcome_page_label.setText(_translate("MainWindow", "Welcome to DataManager application. \n"
" Choice option."))
        self.welcome_page_data_mode_button.setText(_translate("MainWindow", "Data mode"))
        self.welcome_page_cv_mode_button.setText(_translate("MainWindow", "CV mode"))
        self.data_mode_page_file_button.setText(_translate("MainWindow", "Select file"))
        self.label.setText(_translate("MainWindow", "CV MODE PAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
